### PR TITLE
Improved performance for colored graphics

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/PistonDevelopers/gfx_graphics/issues/283

### CODE REVIEW

**Comment by bvssvni** [comment]
I'm getting an `OutOfBounds` when setting `CHUNKS = 1`.

**Comment by bvssvni** [comment]
Found out that `from_raw_parts` should be used instead of `transmute`.

**Comment by bvssvni** [comment]
@mitchmindtree Tested all_widgets example in Conrod. It is a lot faster in both release modes. I don't notice the difference. Feels a little more responsive in debug mode, though.

The deform example is noticeable better in debug mode. In release mode it even runs smoothly with a 40x40 grid, which is significantly better than the old version.

**Comment by bvssvni** [comment]
```
(deform example, 40x40 grid, 1000 frames, benchmark mode)

Old design:

real	2m17.501s
user	2m10.801s
sys	0m5.863s

real	2m18.918s
user	2m12.004s
sys	0m5.952s

New optimization:

real	0m22.146s
user	0m17.496s
sys	0m3.819s

real	0m21.431s
user	0m16.774s
sys	0m3.846s
```

This is a 6.4x speedup!

**Comment by bvssvni** [comment]
Published as 0.23.1.

**Comment by mitchmindtree** [comment]
@bvssvni woah great work, that's super exciting!

I'm currently finishing off some DSP work atm, but will hopefully get back to conrod in the next couple days and try out the update - can't wait!

**Pull request merged**
